### ISSUE TITLE
routes.po not being updated/extracted

### ISSUE THREAD

**Issue by sfusato** [BartOtten/routex#9]
_Used the `routex_example` for this test._

I've created the gettext folders for `en`, `be` locales (`nl` folder was already created) like this:
```elixir
mix gettext.merge priv/gettext --locale en
mix gettext.merge priv/gettext --locale be
```
Next, neither `mix gettext.merge priv/gettext` nor `mix gettext.extract --merge` extracted anything.

There's neither a default/initial `routes.pot` file generated in `priv/gettext`.

What am I missing? Is there some gettext incantation I'm not doing in the right order?

**Comment by BartOtten** [comment]
Away from home without laptop right now, so hard to tell who's to blame for it. I know there were/are [issues with Gettext and extraction ](https://elixirforum.com/t/not-able-to-extract-translations-with-gettext/48749/6 )during compilation.

I did create a 'force' version using a mix task: can you try `mix gettext.extract.routex`?
https://github.com/BartOtten/routex/blob/main/lib/mix/tasks/gettext.extract_routex.ex

**Comment by sfusato** [comment]
1. So, the `routes.pot` isn't extracted at all and neither merged into each locale `.po` files. I've tried with the latest `gettext` release as well as the `main` branch.

```elixir
Warning: PO file priv/gettext/nl/LC_MESSAGES/routes.po has no matching POT file in priv/gettext
```

`default.pot` is extracted and then merged into the `.po` files just fine.

2. Running `mix gettext.extract.routex` brings up this warning without solving the issue:
```elixir
Compiling lib/example_web/router.ex (it's taking more than 10s)
warning: the Gettext backend ExampleWeb.Gettext has the same :priv directory as ExampleWeb.Gettext, which means they will override each other. Please set the :priv option to different directories or use Gettext inside each backend
  (gettext 0.23.0-dev) lib/gettext/extractor.ex:118: anonymous fn/2 in Gettext.Extractor.warn_on_conflicting_backends/1
  (elixir 1.14.0) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
  (gettext 0.23.0-dev) lib/gettext/extractor.ex:103: Gettext.Extractor.pot_files/2
  (gettext 0.23.0-dev) lib/mix/tasks/gettext.extract.ex:109: Mix.Tasks.Gettext.Extract.extract/2
  (gettext 0.23.0-dev) lib/mix/tasks/gettext.extract.ex:68: Mix.Tasks.Gettext.Extract.run/1
  (mix 1.14.0) lib/mix/task.ex:421: anonymous fn/3 in Mix.Task.run_task/4
```
I fail to understand what the warning refers to since it's about the same backend.
